name: Pulumi AWS Deploy
on:
  push:
    branches:
      - master
      - dev
    paths:
      - pulumi/**
      - .github/workflows/**
jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - name: Set TARGET_BRANCH env var
        shell: bash
        run: |
          echo "TARGET_BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set env-specific variables
        shell: bash
        id: vars
        run: |
          if [[ $TARGET_BRANCH == "master" ]] ;
          then
            echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}" >> $GITHUB_ENV
          else
            echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1800
          role-session-name: pulumi-github-preview
          role-skip-session-tagging: true

      - name: Update project infra
        uses: pulumi/actions@v1
        with:
          command: up --non-interactive --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_ROOT: pulumi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send result to MS Teams channel
        uses: opsless/ms-teams-github-actions@main
        if: always() # to let this step always run even if previous step failed
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
